site_name: Notes
repo_url: https://github.com/noreynolds/notes
site_url: https://noreynolds.github.io/notes/

nav:
  - Home: index.md
  - Computer Science:
    - cs/index.md
    - Data Structures: 
      - cs/datastructures/index.md
      - Array: cs/datastructures/array.md
      - Bag: cs/datastructures/bag.md
      - Linked List: cs/datastructures/linkedlist.md
      - Queue: cs/datastructures/queue.md
      - Stack: cs/datastructures/stack.md
    - Algorithms: 
      - cs/algorithms/index.md
      - Insertion: cs/algorithms/insertion.md
      - Merge Sort In Place: cs/algorithms/mergesort_in_place.md
      - Selection: cs/algorithms/selection.md
      - Shell: cs/algorithms/shell.md
      - Top Down Merge Sort: cs/algorithms/top_down_mergesort.md
  - AWS:
    - aws/ccp/aws.md
    - Cloud Practitioner:
      - aws/ccp/index.md
      - Cloud Adoption Framework: aws/ccp/caf.md
      - Well-Architected Framework: aws/ccp/waf.md
      - Services:
        - aws/ccp/services/index.md
        - Analytics: aws/ccp/services/analytics.md 
        - Application Integration: aws/ccp/services/application_integration.md
        - Compute: aws/ccp/services/compute.md
        - Databases: aws/ccp/services/databases.md
        - Dev Tools: aws/ccp/services/dev_tools.md
        - Networking: aws/ccp/services/networking.md
        - Storage: aws/ccp/services/storage.md
        - Security: aws/ccp/services/security.md
      - Exams:
        - aws/ccp/exams/index.md
        - 01/10/2025: aws/ccp/exams/exam_01_10_2025.md
        - 03/19/2025: aws/ccp/exams/exam_03_19_2025.md
theme: 
  name: material
  font:
    code: Roboto Mono
  icon:
    logo: material/library
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.path
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # format: !!python/name:mermaid2.fence_mermaid_custom

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - abbr
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.blocks.definition
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      clickable_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

